import { useState, type ReactNode } from 'react'
import { Bell, Check, Clock, Folder, Refresh, Settings, ShieldLock } from '../components/icons'

const STORAGE_KEY = 'rpngc-settings-v1'
interface SystemSettings { systemName: string; agency: string; timezone: string; supportEmail: string; defaultPriority: string; ageingDays: number; autoAssign: boolean; criticalAlerts: boolean; browserAlerts: boolean; dailyDigest: boolean; unassignedHours: number; requireMfa: boolean; auditLog: boolean; sessionMinutes: number; failedLogins: number; retentionYears: number; attachmentMb: number; exportWatermark: boolean; backups: boolean }
const DEFAULTS: SystemSettings = { systemName: 'Cyber Harassment Reporting', agency: 'RPNGC Cyber Unit', timezone: 'Pacific/Port_Moresby', supportEmail: 'cyberunit@rpngc.gov.pg', defaultPriority: 'medium', ageingDays: 30, autoAssign: false, criticalAlerts: true, browserAlerts: true, dailyDigest: true, unassignedHours: 12, requireMfa: true, auditLog: true, sessionMinutes: 30, failedLogins: 5, retentionYears: 7, attachmentMb: 25, exportWatermark: true, backups: true }
function loadSettings() { try { return { ...DEFAULTS, ...JSON.parse(localStorage.getItem(STORAGE_KEY) || '{}') } as SystemSettings } catch { return DEFAULTS } }
type Tab = 'general' | 'workflow' | 'notifications' | 'security' | 'data'

export default function SettingsPage() {
  const [settings, setSettings] = useState<SystemSettings>(loadSettings)
  const [tab, setTab] = useState<Tab>('general')
  const [status, setStatus] = useState('')
  const update = <K extends keyof SystemSettings>(key: K, value: SystemSettings[K]) => setSettings((current) => ({ ...current, [key]: value }))
  const toggle = (key: keyof SystemSettings, title: string, copy: string) => <label className="setting-toggle-row"><span><strong>{title}</strong><small>{copy}</small></span><input type="checkbox" checked={Boolean(settings[key])} onChange={(event) => setSettings((current) => ({ ...current, [key]: event.target.checked }))} /><i aria-hidden /></label>
  function save() { localStorage.setItem(STORAGE_KEY, JSON.stringify(settings)); setStatus('All changes saved') }
  function restore() { setSettings(DEFAULTS); localStorage.removeItem(STORAGE_KEY); setStatus('Default settings restored') }

  return <div className="settings-page">
    <header className="settings-header"><div><span className="settings-eyebrow"><Settings width={14} height={14} /> System administration</span><h1 className="display">Settings</h1><p>Configure operational defaults, notifications, security and data controls.</p></div><div className="settings-actions"><span role="status">{status && <><Check width={14} height={14} /> {status}</>}</span><button className="secondary" type="button" onClick={restore}><Refresh width={15} height={15} /> Restore defaults</button><button type="button" onClick={save}>Save changes</button></div></header>
    <section className="settings-summary"><article><span><ShieldLock width={18} height={18} /></span><div><strong>Protected configuration</strong><small>Administrator access required</small></div></article><article><span><Check width={18} height={18} /></span><div><strong>Audit logging active</strong><small>All changes are recorded</small></div></article><article><span><Clock width={18} height={18} /></span><div><strong>Last updated</strong><small>15 Jul 2026 · 09:42</small></div></article></section>
    <div className="settings-workspace">
      <nav className="settings-tabs" aria-label="Settings sections">{([['general', Settings, 'General'], ['workflow', Folder, 'Case workflow'], ['notifications', Bell, 'Notifications'], ['security', ShieldLock, 'Security'], ['data', Refresh, 'Data & retention']] as const).map(([key, Icon, label]) => <button key={key} type="button" className={tab === key ? 'active' : ''} onClick={() => setTab(key)}><Icon width={17} height={17} /><span>{label}</span></button>)}</nav>
      <section className="settings-panel">
        {tab === 'general' && <><PanelHead eyebrow="Workspace" title="General configuration" copy="Core identity and regional settings used throughout the dashboard." /><div className="settings-form-grid"><Field label="System name"><input value={settings.systemName} onChange={(e) => update('systemName', e.target.value)} /></Field><Field label="Agency / unit"><input value={settings.agency} onChange={(e) => update('agency', e.target.value)} /></Field><Field label="Timezone"><select value={settings.timezone} onChange={(e) => update('timezone', e.target.value)}><option>Pacific/Port_Moresby</option><option>Australia/Brisbane</option><option>UTC</option></select></Field><Field label="Support email"><input type="email" value={settings.supportEmail} onChange={(e) => update('supportEmail', e.target.value)} /></Field></div></>}
        {tab === 'workflow' && <><PanelHead eyebrow="Case management" title="Workflow defaults" copy="Define how new cases enter and move through the investigation pipeline." /><div className="settings-form-grid"><Field label="Default priority"><select value={settings.defaultPriority} onChange={(e) => update('defaultPriority', e.target.value)}><option value="low">Low</option><option value="medium">Medium</option><option value="high">High</option><option value="critical">Critical</option></select></Field><Field label="Ageing alert threshold (days)"><input type="number" min="1" value={settings.ageingDays} onChange={(e) => update('ageingDays', Number(e.target.value))} /></Field></div><div className="settings-toggle-group">{toggle('autoAssign', 'Automatic officer assignment', 'Assign new complaints to the available officer with the lowest workload.')}</div></>}
        {tab === 'notifications' && <><PanelHead eyebrow="Operational awareness" title="Alert delivery" copy="Control when and how the Cyber Unit receives dashboard notifications." /><div className="settings-form-grid compact"><Field label="Unassigned case alert (hours)"><input type="number" min="1" value={settings.unassignedHours} onChange={(e) => update('unassignedHours', Number(e.target.value))} /></Field></div><div className="settings-toggle-group">{toggle('criticalAlerts', 'Critical-risk alerts', 'Notify administrators immediately when a critical case is filed.')}{toggle('browserAlerts', 'Browser alerts', 'Display real-time alerts on authorised dashboard sessions.')}{toggle('dailyDigest', 'Daily summary', 'Send an operational summary at the close of each duty day.')}</div></>}
        {tab === 'security' && <><PanelHead eyebrow="Access protection" title="Security controls" copy="Apply account and session protections across all authorised users." /><div className="settings-form-grid"><Field label="Session timeout (minutes)"><input type="number" min="5" value={settings.sessionMinutes} onChange={(e) => update('sessionMinutes', Number(e.target.value))} /></Field><Field label="Failed login limit"><input type="number" min="3" value={settings.failedLogins} onChange={(e) => update('failedLogins', Number(e.target.value))} /></Field></div><div className="settings-toggle-group">{toggle('requireMfa', 'Require multi-factor authentication', 'Enforce MFA for every privileged and operational account.')}{toggle('auditLog', 'Security audit logging', 'Record sign-ins, account changes, exports and permission updates.')}</div></>}
        {tab === 'data' && <><PanelHead eyebrow="Information governance" title="Data & retention" copy="Control storage limits, exports and records retention." /><div className="settings-form-grid"><Field label="Case retention (years)"><input type="number" min="1" value={settings.retentionYears} onChange={(e) => update('retentionYears', Number(e.target.value))} /></Field><Field label="Maximum attachment (MB)"><input type="number" min="1" value={settings.attachmentMb} onChange={(e) => update('attachmentMb', Number(e.target.value))} /></Field></div><div className="settings-toggle-group">{toggle('exportWatermark', 'Restricted export watermark', 'Mark every generated report as restricted internal material.')}{toggle('backups', 'Automatic encrypted backups', 'Create a protected backup of operational records each night.')}</div></>}
      </section>
    </div>
  </div>
}

function PanelHead({ eyebrow, title, copy }: { eyebrow: string; title: string; copy: string }) { return <div className="settings-panel-head"><span>{eyebrow}</span><h2>{title}</h2><p>{copy}</p></div> }
function Field({ label, children }: { label: string; children: ReactNode }) { return <label><span>{label}</span>{children}</label> }
